export const DEFAULT_RESULT_LIMIT = 10;
export const MAXIMUM_RESULT_LIMIT = 100;

export const DEFAULT_CONTEXT_CHUNKS_BEFORE = 1;
export const DEFAULT_CONTEXT_CHUNKS_AFTER = 1;
export const DEFAULT_MAXIMUM_CONTEXT_CHARACTERS = 4_000;

export const MAXIMUM_CONTEXT_CHUNKS_PER_DIRECTION = 20;
export const MAXIMUM_CONTEXT_CHARACTERS = 100_000;

export const DEFAULT_RERANKING_CANDIDATE_MULTIPLIER = 5;
export const MAXIMUM_RERANKING_CANDIDATES = 100;
