export const DEFAULT_OPENAI_COMPATIBLE_BASE_URL = "http://127.0.0.1:1234/v1";

/** @deprecated Use DEFAULT_OPENAI_COMPATIBLE_BASE_URL. */
export const DEFAULT_LM_STUDIO_BASE_URL = DEFAULT_OPENAI_COMPATIBLE_BASE_URL;
